{
  "title": "<Itoshiki Ningyo>",
  "description": "<Umi, a tattoo artist who carries a mermaid’s curse, was born with a jet black right eye, and hid the right side of his body which carried an ugly birthmark from the curse. In order to hide this birthmark which even his parents despised, he covered it with a beautiful tattoo, and continued to live his life while hiding himself from the world. However, a chance encounter with a swindling spirit medium changed his life.


This is a once-in-a-lifetime love of a young man who was called a monster."	>",
  "artist": "<Hijiki>",
  "author": "<Hijiki
  "cover": "<https://cdn.discordapp.com/attachments/403211718001557506/866478730736959488/GGScansBL_Itoshiki-Ningyo_v01_ch01_cover_a.png>",
  "chapters": {
    "<chapter number>": {
      "title": "<Chapter 1>",
      "volume": "<1>",
      "groups": {
        "<group name>": "/proxy/api/imgur/chapter/<2uXLOFF>/"
      },
      "last_updated": "1616368746"
    }
  }
}
